remote_theme: daviddarnes/alembic

name : Boynux
brand : Boynux
description : The way it works ...
url : "https://www.boynux.com"
email : reachme@boynu.com
author: Boynux

defaults:
  - scope:
      type: ""
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      relate: true

permalink: /:title/

exclude : [ README.md , version.txt ]

jekyll-mentions: https://twitter.com
twitter:
    username: _boynux_

paginate: 10
paginate_path: page:num

alert : false
notice : false
comments: true

social:
  name: Mohamad Arab
  links:
    - https://twitter.com/_boynux_
    - https://www.facebook.com/boynux
    - https://www.linkedin.com/in/boynux
    - https://plus.google.com/+boynux
    - https://github.com/boynux

collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text: |
      Welcome to the blog

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/_boynux_
  LinkedIn: https://www.linkedin.com/in/boynux
  Google+: https://plus.google.com/+Boynux
  GitHub: https://github.com/boynux
  link: https://boynux.com
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Google+: "#DC4E41"

avatarurl: /img/boynux-16.png

# 8. Site navigation
navigation_header:
  Home: /
  Categories: /categories/
  Search: /search/

disqus: boynux
google_analytics: UA-60601499-1

include: [".well-known"]

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-default-layout
  - jekyll-feed
  - jemoji

